Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -56,6 +56,13 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
 
+    # Set ECR variables
+    - name: Set ECR Variables
+      run: |
+        echo "ECR_REGISTRY=682033487579.dkr.ecr.ap-northeast-1.amazonaws.com" >> $GITHUB_ENV
+        echo "ECR_REPOSITORY=${{ secrets.REPOSITORY_NAME }}" >> $GITHUB_ENV
+        echo "IMAGE_TAG=latest" >> $GITHUB_ENV
+
     # Debugging the ECR registry and repository
     - name: Debug ECR Registry and Repository
       run: |
@@ -63,11 +70,15 @@ jobs:
         echo "ECR Repository: $ECR_REPOSITORY"
         echo "Image Tag: $IMAGE_TAG"
 
+    # Check if variables are set correctly
+    - name: Check if ECR Registry and Repository are set
+      run: |
+        if [[ -z "$ECR_REGISTRY" || -z "$ECR_REPOSITORY" || -z "$IMAGE_TAG" ]]; then
+          echo "Error: Missing required variables!"
+          exit 1
+        fi
+
     - name: Build and push the tagged docker image to Amazon ECR
-      env:
-        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: ${{ secrets.REPOSITORY_NAME }}
-        IMAGE_TAG: latest
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
